install.packages("dplyr")
install.packages("edgeR")
install.packages("sva")
install.packages("tibble")
install.packages("data.table")
install.packages("stringr")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("BioinformaticsFMRP/TCGAbiolinksGUI.data")
BiocManager::install("BioinformaticsFMRP/TCGAbiolinks")
install.packages("biomaRt")
install.packages("cluster")
install.packages("ComplexHeatmap")
install.packages("circlize")
install.packages("viridisLite")
